
package it.polito.dp2.PJS.sol6.client1.wsimport;

import java.math.BigInteger;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PJSMaster", targetNamespace = "http://service.sol6.PJS.dp2.polito.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PJSMaster {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigInteger
     * @throws NoFreeExecutionHost_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submit", targetNamespace = "http://service.sol6.PJS.dp2.polito.it/", className = "it.polito.dp2.PJS.sol6.client1.wsimport.Submit")
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "http://service.sol6.PJS.dp2.polito.it/", className = "it.polito.dp2.PJS.sol6.client1.wsimport.SubmitResponse")
    @Action(input = "http://service.sol6.PJS.dp2.polito.it/PJSMaster/submitRequest", output = "http://service.sol6.PJS.dp2.polito.it/PJSMaster/submitResponse", fault = {
        @FaultAction(className = NoFreeExecutionHost_Exception.class, value = "http://service.sol6.PJS.dp2.polito.it/PJSMaster/submit/Fault/NoFreeExecutionHost")
    })
    public BigInteger submit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws NoFreeExecutionHost_Exception
    ;

    /**
     * 
     * @return
     *     returns it.polito.dp2.PJS.sol6.client1.wsimport.GetHostsResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHosts", targetNamespace = "http://service.sol6.PJS.dp2.polito.it/", className = "it.polito.dp2.PJS.sol6.client1.wsimport.GetHosts")
    @ResponseWrapper(localName = "getHostsResponse", targetNamespace = "http://service.sol6.PJS.dp2.polito.it/", className = "it.polito.dp2.PJS.sol6.client1.wsimport.GetHostsResponse")
    @Action(input = "http://service.sol6.PJS.dp2.polito.it/PJSMaster/getHostsRequest", output = "http://service.sol6.PJS.dp2.polito.it/PJSMaster/getHostsResponse")
    public it.polito.dp2.PJS.sol6.client1.wsimport.GetHostsResponse.Return getHosts();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHostNames", targetNamespace = "http://service.sol6.PJS.dp2.polito.it/", className = "it.polito.dp2.PJS.sol6.client1.wsimport.GetHostNames")
    @ResponseWrapper(localName = "getHostNamesResponse", targetNamespace = "http://service.sol6.PJS.dp2.polito.it/", className = "it.polito.dp2.PJS.sol6.client1.wsimport.GetHostNamesResponse")
    @Action(input = "http://service.sol6.PJS.dp2.polito.it/PJSMaster/getHostNamesRequest", output = "http://service.sol6.PJS.dp2.polito.it/PJSMaster/getHostNamesResponse")
    public List<String> getHostNames();

}
